{"name": "Login with valid phone number and invalid password -- @1.2 ", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.NoSuchWindowException: Message: no such window: target window already closed\nfrom unknown error: web view not found\n  (Session info: chrome=115.0.5790.171)\nStacktrace:\nBacktrace:\n\tGetHandleVerifier [0x00007FF674144A62+57106]\n\t(No symbol) [0x00007FF6740BCF52]\n\t(No symbol) [0x00007FF673F8E2CB]\n\t(No symbol) [0x00007FF673F6DEB9]\n\t(No symbol) [0x00007FF673FEAE07]\n\t(No symbol) [0x00007FF673FFDBEF]\n\t(No symbol) [0x00007FF673FE6793]\n\t(No symbol) [0x00007FF673FBCE81]\n\t(No symbol) [0x00007FF673FBE064]\n\tGetHandleVerifier [0x00007FF6743F4222+2873042]\n\tGetHandleVerifier [0x00007FF674446590+3209792]\n\tGetHandleVerifier [0x00007FF67443F3AF+3180639]\n\tGetHandleVerifier [0x00007FF6741D5F25+652245]\n\t(No symbol) [0x00007FF6740C8618]\n\t(No symbol) [0x00007FF6740C47C4]\n\t(No symbol) [0x00007FF6740C48BC]\n\t(No symbol) [0x00007FF6740B4C33]\n\tBaseThreadInitThunk [0x00007FF965F37614+20]\n\tRtlUserThreadStart [0x00007FF967EE26B1+33]\n\n", "trace": "  File \"C:\\Users\\lmallikarjuna\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\behave\\runner.py\", line 545, in run_hook\n    self.hooks[name](context, *args)\n  File \"features\\environment.py\", line 27, in after_step\n    allure.attach(context.driver.get_screenshot_as_png(),\n                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\lmallikarjuna\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 836, in get_screenshot_as_png\n    return b64decode(self.get_screenshot_as_base64().encode(\"ascii\"))\n                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\lmallikarjuna\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 847, in get_screenshot_as_base64\n    return self.execute(Command.SCREENSHOT)[\"value\"]\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\lmallikarjuna\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 345, in execute\n    self.error_handler.check_response(response)\n  File \"C:\\Users\\lmallikarjuna\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 229, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "steps": [{"name": "Given I navigated to Login page", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.NoSuchWindowException: Message: no such window: target window already closed\nfrom unknown error: web view not found\n  (Session info: chrome=115.0.5790.171)\nStacktrace:\nBacktrace:\n\tGetHandleVerifier [0x00007FF674144A62+57106]\n\t(No symbol) [0x00007FF6740BCF52]\n\t(No symbol) [0x00007FF673F8E2CB]\n\t(No symbol) [0x00007FF673F6DEB9]\n\t(No symbol) [0x00007FF673FEAE07]\n\t(No symbol) [0x00007FF673FFDBEF]\n\t(No symbol) [0x00007FF673FE6793]\n\t(No symbol) [0x00007FF673FBCE81]\n\t(No symbol) [0x00007FF673FBE064]\n\tGetHandleVerifier [0x00007FF6743F4222+2873042]\n\tGetHandleVerifier [0x00007FF674446590+3209792]\n\tGetHandleVerifier [0x00007FF67443F3AF+3180639]\n\tGetHandleVerifier [0x00007FF6741D5F25+652245]\n\t(No symbol) [0x00007FF6740C8618]\n\t(No symbol) [0x00007FF6740C47C4]\n\t(No symbol) [0x00007FF6740C48BC]\n\t(No symbol) [0x00007FF6740B4C33]\n\tBaseThreadInitThunk [0x00007FF965F37614+20]\n\tRtlUserThreadStart [0x00007FF967EE26B1+33]\n\n", "trace": "  File \"C:\\Users\\lmallikarjuna\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\behave\\runner.py\", line 545, in run_hook\n    self.hooks[name](context, *args)\n  File \"features\\environment.py\", line 27, in after_step\n    allure.attach(context.driver.get_screenshot_as_png(),\n                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\lmallikarjuna\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 836, in get_screenshot_as_png\n    return b64decode(self.get_screenshot_as_base64().encode(\"ascii\"))\n                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\lmallikarjuna\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 847, in get_screenshot_as_base64\n    return self.execute(Command.SCREENSHOT)[\"value\"]\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\lmallikarjuna\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 345, in execute\n    self.error_handler.check_response(response)\n  File \"C:\\Users\\lmallikarjuna\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 229, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1691585142182, "stop": 1691585142245}, {"name": "When I enter valid phone number as \"6303169446\" and invalid password as \"srikala12055\" into the fields", "status": "skipped", "start": 1691585146297, "stop": 1691585146297}, {"name": "And I click on Login button", "status": "skipped", "start": 1691585146297, "stop": 1691585146297}, {"name": "Then I should get a proper warning message on password page", "status": "skipped", "start": 1691585146297, "stop": 1691585146297}], "parameters": [{"name": "number", "value": "6303169446"}, {"name": "password", "value": "srikala12055"}], "start": 1691585125175, "stop": 1691585146297, "uuid": "ff48f38f-102d-48a2-b878-eccd59c5c534", "historyId": "2fb7451940dcb63528d78aa090e39ab2", "fullName": "Login Functionality: Login with valid phone number and invalid password", "labels": [{"name": "severity", "value": "normal"}, {"name": "tag", "value": "login"}, {"name": "feature", "value": "Login Functionality"}, {"name": "framework", "value": "behave"}, {"name": "language", "value": "cpython3"}]}